Feature/scrum 43  block users with unverified email
Misha2048/CatharsisX-front pull request #31
Opened 2024-01-01 12:11 UTC by N0UNe1m

2024-01-01 12:19 UTC, Misha2048 requested changes
Smells like shit, like

2024-01-01 12:19 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +  const handleResendVerification = async () => {
UseCallback

2024-01-01 12:19 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +    }, 2000)
Можно поставить поллинг на меньшее количество секунд, чтоб кратно снизить нагрузку на сервер

2024-01-01 12:19 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +        <Form>
Зачем форма?

2024-01-01 12:19 UTC, Misha2048 commented on src/helpers/makeGetRequest.ts
> +async function makeGetRequest(dispatch: Dispatch) {
Несемантичная сигнатура

2024-01-01 12:19 UTC, Misha2048 commented on src/helpers/makeGetRequest.ts
> +    const response = await api.users.me()
Несемантичная сигнатура

2024-01-01 12:19 UTC, Misha2048 commented on src/redux/slices/UserSlice.ts
> +      setValue: (state, action: {payload: PropertyType, type: string}) => {
Совершенно бредовый экшн, неоднократно просил переделать

2024-01-09 09:09 UTC, Misha2048 requested changes
Everything is ok, but some moments

2024-01-09 09:09 UTC, Misha2048 commented on src/helpers/getEmailStatusAndChangeStore.ts
> +    console.error('Ошибка при выполнении запроса:', error)
ru -> en

2024-01-09 09:09 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +// const dispatch = useDispatch()
Please use useDispatch

2024-01-09 09:09 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +  const handleResendVerification = async () => {
Please use useCallback

2024-01-09 09:09 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +      console.log('Email verification sent successfully.')
Remove logs

2024-01-09 09:09 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +          window.location.href = '/'
please use useNavigate

2024-01-09 09:09 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +        const isEmailVerified = await store.dispatch(getEmailStatusAndChangeStore)
useDispatch

2024-01-09 09:09 UTC, Misha2048 commented on src/components/CheckVerify.tsx
> +      console.error('Error sending email verification:', error)
Remove logs

2024-01-09 09:09 UTC, Misha2048 commented on src/helpers/getEmailStatusAndChangeStore.ts
> +    const responseFromMe = await api.users.me()
Please set consistent signature

2024-01-10 19:57 UTC, holotsvan approved these changes

2024-01-10 20:00 UTC, Misha2048 approved these changes

2024-01-10 20:00 UTC, Misha2048 commented on src/helpers/getEmailStatusAndChangeStore.ts
> +    const responseDataFromUsersMe = await api.users.me()
Можно эту сороконожку обозвать user?

2024-01-10 20:01 UTC, N0UNe1m commented on src/helpers/getEmailStatusAndChangeStore.ts
> +    const responseDataFromUsersMe = await api.users.me()
ok

2024-01-10 20:26 UTC, merged